root: true
env:
  browser: true
  node: true
settings:
  react:
    version: '16.13.1'
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
plugins:
  - '@typescript-eslint'
  - react
rules:
  prettier/prettier:
    - error
    - endOfLine: auto
