version: '3.4'

services:
  nginx:
    container_name: nginx
    build: ./.nginx
    depends_on:
      - client
      - server
    volumes:
      - ./client/build:/var/www/public
    ports:
      - '80:80'
  
  client:
    build: 
      context: ./client
      target: prod

  server:
    build: 
      context: ./server
      target: prod