version: '3.4'

networks:
  server:
  client:

services:
  nginx:
    container_name: nginx
    build: ./config/nginx
    depends_on:
      - client
      - server
    volumes:
      - ./client/build:/var/www/public
    ports:
      - '80:80'
    networks:
      - client
      - server
  
  client:
    stdin_open: false
    build: 
      context: ./client
      target: prod
    networks:
      - client
    environment:
      CHOKIDAR_USEPOLLING: 'false'

  server:
    stdin_open: false
    build: 
      context: ./server
      target: prod
    networks:
      - server
    environment:
      CHOKIDAR_USEPOLLING: 'false'