version: '3.4'

services:
  client:
    container_name: client
    stdin_open: true
    depends_on:
      - server
    build: 
      context: ./client
      target: dev
    volumes:
      - ./client:/usr/src/app/client
    ports:
      - '3000:3000'

  server:
    container_name: server
    build: 
      context: ./server
      target: dev
    depends_on:
      - database
      - redis
    volumes:
      - ./server:/usr/src/app/server
      - ./.config:/usr/src/app/.config
    env_file: ./.config/.env
    ports:
      - '5000:5000'
  
  database:
    container_name: database
    image: postgres
    volumes:
      - data:/var/lib/postgres/data
    ports:
      - '5432:5432'
    env_file: ./.config/.env

  redis:
    container_name: redis
    build: ./.redis
    ports:
      - '6379:6379'

volumes:
  data: