version: '3'

services:
  nginx:
    container_name: nginx
    build: ./.nginx
    depends_on:
      - client
      - server
    volumes:
      - ./client/build:/var/www/public
    ports:
      - '80:80'
  
  client:
    environment:
      NODE_ENV: production

  server:
    environment:
      NODE_ENV: production