version: '3'

services:
  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - '3000:3000'

  server:
    container_name: server
    build: ./server
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
    environment:
      DATABASE_URL: postgres://user:pass@database:5432/db
    ports:
      - '5000:5000'
  
  db:
    container_name: database
    image: postgres
    volumes:
      - data:/var/lib/postgres/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

volumes:
  data: