version: '3.4'

services:
  client:
    container_name: client
    stdin_open: true
    depends_on:
      - server
    build: 
      context: ./client
      target: dev
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules/
    ports:
      - '3000:3000'
    environment:
      CHOKIDAR_USEPOLLING: 'true'

  server:
    container_name: server
    stdin_open: true
    build: 
      context: ./server
      target: dev
    depends_on:
      - database
      - redis
    volumes:
      - ./server:/usr/src/app/server
      - ./config:/usr/src/app/config
      - /usr/src/app/server/node_modules/
    env_file: ./.env
    ports:
      - '5000:5000'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
  
  database:
    container_name: database
    image: postgres
    volumes:
      - data:/var/lib/postgres/data
    ports:
      - '5432:5432'
    env_file: ./.env

  redis:
    container_name: redis
    build: ./config/redis
    ports:
      - '6379:6379'

volumes:
  data: