version: '3'

services:
  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/usr/src/app/client
    ports:
      - '3000:3000'

  server:
    container_name: server
    build: ./server
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app/server
      - ./.config:/usr/src/app/.config
    env_file: ./.config/.env
    ports:
      - '5000:5000'
  
  db:
    container_name: database
    image: postgres
    volumes:
      - data:/var/lib/postgres/data
    ports:
      - '5432:5432'
    env_file: ./.config/.env

volumes:
  data: